# Generated by Django 5.2 on 2025-04-25 18:16

import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('summary', models.TextField()),
                ('desccription', django_quill.fields.QuillField()),
            ],
        ),
    ]
